name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Cache Docker
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with: 
        key: docker
        path: ~/.docker
    - name: Run Tests
      run: go test .
    - name: Login to Docker Hub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --cache-to type=gha --cache-from type=gha --push --tag ghcr.io/${{ github.repository }}:${{ github.sha }}
 
